spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          username: ${GITHUB_USER}
          password: ${GITHUB_PASS}
          default-label: main
          uri: https://github.com/Duduxs/ds-course-config-ms

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_REGISTRY_URL:http://localhost:8761/eureka}
