server:
  port: 8080

spring:
  application:
    name: ms-api-gateway
  cloud:
    gateway:
      routes:
        - id: gateway-ms-worker
          uri: lb://ms-worker
          predicates:
            - Path=/ms-worker/**
        - id: gateway-ms-payroll
          uri: lb://ms-payroll
          predicates:
            - Path=/ms-payroll/**
        - id: gateway-ms-user
          uri: lb://ms-user
          predicates:
            - Path=/ms-user/**
        - id: gateway-ms-oauth
          uri: lb://ms-oauth
          predicates:
            - Path=/ms-oauth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka