server:
  port: ${PORT:0}
  servlet:
    context-path: '/ms-payroll/'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: ms-payroll

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 5s
  circuitbreaker:
    instances:
      circuitbreakerInstance:
        slidingWindowSize: 30
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 45s
        failureRateThreshold: 80