server:
  port: ${PORT:0}
  servlet:
    context-path: '/ms-payroll/'

spring:
  application:
    name: ms-payroll
  profiles:
    active: ${ENV:dev}
  config:
    import: ${CONFIG_SERVER_URL:configserver:}

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 5s
  circuitbreaker:
    instances:
      circuitbreakerInstance:
        slidingWindowSize: 30
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 45s
        failureRateThreshold: 80