server:
  port: ${PORT:0}
  servlet:
    context-path: '/ms-oauth/'

spring:
  application:
    name: ms-oauth
  profiles:
    active: ${ENV:dev}
  config:
    import: ${CONFIG_SERVER_URL:configserver:}