server:
  port: ${PORT:0}
  servlet:
    context-path: '/ms-worker/'

spring:
  application:
    name: ms-worker
  profiles:
    active: ${ENV:dev}
  config:
    import: ${CONFIG_SERVER_URL:configserver:}
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
