server:
  port: ${PORT:0}
  servlet:
    context-path: '/ms-user/'

spring:
  application:
    name: ms-user
  profiles:
    active: ${ENV:dev}
  config:
    import: ${CONFIG_SERVER_URL:configserver:}
  jpa:
    open-in-view: false