# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build Eureka Server with Maven
      run: mvn -B package --file ms-eureka-server/pom.xml
    - name: Build Config Server with Maven
      run: mvn -B package --file ms-config-server/pom.xml
    - name: Build Api Gateway with Maven
      run: mvn -B package --file api-gateway/pom.xml
    - name: Build Oauth with Maven
      run: mvn -B package --file ms-oauth/pom.xml
    - name: Build Payroll with Maven
      run: mvn -B package --file ms-payroll/pom.xml
    - name: Build User with Maven
      run: mvn -B package --file ms-user/pom.xml
    - name: Build Worker with Maven
      run: mvn -B package --file ms-worker/pom.xml
